/* Program to show the header contents of the packets generated by unb.
 * pep/09Jul14
 */

#include <stdio.h>
#include <errno.h>
#include <errno.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <string.h>
#include <netdb.h>

// Data format of the AARTFAAC Uniboard output packets.
typedef struct                                                                     
{ unsigned long long rsp_reserved_1:59;
  unsigned int rsp_rsp_clock:1;
  unsigned int rsp_sdo_mode:2;
  unsigned int rsp_lane_id:2;
  unsigned int rsp_station_id:16;
  unsigned int nof_words_per_block:16; // 8sbbands X 96 dipoles=768 (4B = 1 word)  
  unsigned int nof_blocks_per_packet:16;// 2                                       
  unsigned int rsp_sync:1;
  unsigned int rsp_reserved_0:13;
  unsigned long long rsp_bsn:50;        // Two timeslices share the same BSN       
}__attribute ((__packed__)) UniHdrType ;                                                  
                                                                                   
#define NRUNISUBBANDS 8                                                            
#define NRUNIDIPOLES 96                                                               
/* Uniboard data format:
 UDPhdr->userhdr(22B)->
 |d0_sb0_t0_p0_[r,i]...d95_sb0_t0_p1_[r,i]|... //subband 0
 |d0_sb7_t0_p1_[r,i]...d95_sb7_t0_p1_[r,i]|... // ts0

 |d0_sb0_t1_p0_[r,i]...d95_sb0_t1_p1_[r,i]|...
 |d0_sb7_t1_p0_[r,i]...d95_sb7_t1_p1_[r,i]|    // ts1
 d = dipole 0-95, p = pol 0 or 1 of an antenna, sb = subband, t = time sample,
 [r,i] = real/imag.
 1 UDP packet = 2 timeslices, 8 subbands, 96 dipoles.
*/
typedef struct                                                                     
{ short data [NRUNISUBBANDS*NRUNIDIPOLES*4];    
} UniBlkType;                                                                      
                                                                                   
typedef struct                                                                     
{ UniHdrType hdr;
  UniBlkType blk[2]; // Two timeslices
} UniUDPPktType;


int Done = 0;
int main (int argc, char *argv[])
{ 	FILE *fin[4] = {NULL,};
  	int i=0, nvalidfiles=1, pktno=0, rd=0;
 	UniUDPPktType *uni = NULL;

  	if ((uni=(UniUDPPktType*) calloc (sizeof (UniUDPPktType), nvalidfiles)) == NULL)
    { perror ("calloc"); return -1;}

	struct sockaddr_storage their_addr;
    socklen_t addr_size;
    struct addrinfo hints, *res;
    int sockfd, new_fd;
	int fromlen = 0, rx=0;
	char ip[] = "10.99.100.1";
	char port[] = "53308";

    memset(&hints, 0, sizeof hints);
    hints.ai_family = AF_UNSPEC;  // use IPv4 or IPv6, whichever
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;     // fill in my IP for me
    
    getaddrinfo(NULL, port, &hints, &res);
   
    // make a socket, bind it, and listen on it:
    sockfd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
    bind(sockfd, res->ai_addr, res->ai_addrlen);
    listen(sockfd, 100);

	addr_size = sizeof their_addr;
    new_fd = accept(sockfd, (struct sockaddr *)&their_addr, &addr_size);

	for (i=0; i<100; i++)
	{ if ((rx=recvfrom(new_fd, (unsigned char*)uni, sizeof (UniUDPPktType), 0, 
             (struct sockaddr *)&their_addr, &fromlen)) == sizeof (UniUDPPktType));
	  
	  fprintf (stderr, "0x%0llx \n", uni[0].hdr.rsp_bsn); 
 	}

  return 0;
}
