% Script to convert the output of rdgpuvis.c to something that showgpuacm.m can digest.
% showgpuacm.m takes the output of gpu2mat.py, but this is showing inconsistent results
% on the waveform generator test data.
% pep/14Oct14

% tmp = load ('14Oct14_122226.dat');
tmp = load ('try3_14Oct14_092622.dat');
% tmp = load ('14Oct14_romein_nomiss.dat');
acm = zeros (1, 41616, 63, 4, 2); % As generated by gpu2mat.py (tim, bline, chan, pol, re/im)
acm (1,:,:,1,1) = tmp(:,3:8:end)'; % First two columns are tstamp and chanstamp. Real comes first
acm (1,:,:,1,2) = tmp(:,4:8:end)'; 

acm (1,:,:,2,1) = tmp(:,5:8:end)'; % First two columns are tstamp and chanstamp. Real comes first
acm (1,:,:,2,2) = tmp(:,6:8:end)'; 

acm (1,:,:,3,1) = tmp(:,7:8:end)'; % First two columns are tstamp and chanstamp. Real comes first
acm (1,:,:,3,2) = tmp(:,8:8:end)'; 

acm (1,:,:,4,1) = tmp(:,9:8:end)'; % First two columns are tstamp and chanstamp. Real comes first
acm (1,:,:,4,2) = tmp(:,10:8:end)'; 

t1 = triu(ones (288));
t2 = t1; t3 = t1; t4 =t1;
t1(t1==1) = squeeze (complex (acm(1,:,42,1,1), acm(1,:,42,1,2)));
t2(t2==1) = squeeze (complex (acm(1,:,42,2,1), acm(1,:,42,2,2)));
t3(t3==1) = squeeze (complex (acm(1,:,42,3,1), acm(1,:,42,3,2)));
t4(t4==1) = squeeze (complex (acm(1,:,42,4,1), acm(1,:,42,4,2)));
