/* Program to show the header contents of the packets generated by unb.
 * pep/09Jul14
 */

#include <stdio.h>
#include <errno.h>
#include <errno.h>
#include <stdlib.h>
#include <arpa/inet.h>

// Data format of the AARTFAAC Uniboard output packets.
typedef struct                                                                     
{ unsigned long long rsp_reserved_1:59;
  unsigned int rsp_rsp_clock:1;
  unsigned int rsp_sdo_mode:2;
  unsigned int rsp_lane_id:2;
  unsigned int rsp_station_id:16;
  unsigned int nof_words_per_block:16; // 8sbbands X 96 dipoles=768 (4B = 1 word)  
  unsigned int nof_blocks_per_packet:16;// 2                                       
  unsigned int rsp_sync:1;
  unsigned int rsp_reserved_0:13;
  unsigned long long rsp_bsn:50;        // Two timeslices share the same BSN       
}__attribute ((__packed__)) UniHdrType ;                                                  
                                                                                   
#define NRUNISUBBANDS 8                                                            
#define NRUNIDIPOLES 96                                                               
/* Uniboard data format:
 UDPhdr->userhdr(22B)->
 |d0_sb0_t0_p0_[r,i]...d95_sb0_t0_p1_[r,i]|... //subband 0
 |d0_sb7_t0_p1_[r,i]...d95_sb7_t0_p1_[r,i]|... // ts0

 |d0_sb0_t1_p0_[r,i]...d95_sb0_t1_p1_[r,i]|...
 |d0_sb7_t1_p0_[r,i]...d95_sb7_t1_p1_[r,i]|    // ts1
 d = dipole 0-95, p = pol 0 or 1 of an antenna, sb = subband, t = time sample,
 [r,i] = real/imag.
 1 UDP packet = 2 timeslices, 8 subbands, 96 dipoles.
*/
typedef struct                                                                     
{ short data [NRUNISUBBANDS*NRUNIDIPOLES*2];    
} UniBlkType;                                                                      
                                                                                   
typedef struct                                                                     
{ UniHdrType hdr;
  UniBlkType blk[2]; // Two timeslices
} UniUDPPktType;


int Done = 0;
int main (int argc, char *argv[])
{ FILE *fin[4] = {NULL,};
  int i=0, j=0, nvalidfiles=0, pktno=0, rd=0;
  UniUDPPktType *uni = NULL;
  unsigned short lochdr[11]; // 22Byte SDO header
  UniHdrType *uptr = (UniHdrType*) lochdr;
  unsigned short *sptr = NULL;

  for (i=0; i<argc-1; i++)
  { if ((fin[i]=fopen (argv[i+1], "rb")) == NULL)
    { fprintf (stderr, "Error in opening %s.\n", argv[i+1]);}
	else nvalidfiles++;
  }
  fprintf (stderr, "Found  %d valid files.\n", nvalidfiles);

  if ((uni=(UniUDPPktType*) calloc (sizeof (UniUDPPktType), nvalidfiles)) == NULL)
  { perror ("calloc"); return -1;}

  while (Done==0)
  { fprintf (stderr, "%6d ", pktno);
	i = 0;
	for (i=0; i<nvalidfiles; i++)
    { if ((rd=fread ((unsigned char*)(uni+i), 1, sizeof (UniUDPPktType), fin[i])) 
		 != sizeof (UniUDPPktType)) 
	  { fprintf (stderr, "Error in reading from file %d.\n", i); Done=1; break;}

      sptr = (unsigned short*)(&uni[i].hdr);
      for (j=0; j<11; j++)
        lochdr[j] = ntohs(sptr[j]);

      fprintf (stderr, "clk: %d, mode: %d, lane: %d, station: %d, w2blk: %d, b2pkt: %d, bsn: 0x%LX", uptr->rsp_rsp_clock, uptr->rsp_sdo_mode, uptr->rsp_lane_id, uptr->rsp_station_id, uptr->nof_words_per_block, uptr->nof_blocks_per_packet, uptr->rsp_bsn);
	  // fprintf (stderr, "%llu/0x%LX ", uni[i].hdr.rsp_bsn, uni[i].hdr.rsp_bsn); 
    }
	fprintf (stderr, "\n");
    pktno++;
  }

  return 0;
}
